const { SlashCommandBuilder, PermissionFlagsBits, ChannelType } = require("discord.js");
const handlers={autorol:require("../../Utils/SetupHandlers/autoRoleUB"),"boost-preview":require("../../Utils/SetupHandlers/boostPreview"),boost:require("../../Utils/SetupHandlers/boostSetUp"),confesiones:require("../../Utils/SetupHandlers/confesionesSetUp"),contador:require("../../Utils/SetupHandlers/countingSetUp"),salidas:require("../../Utils/SetupHandlers/leaveSetUp"),reportes:require("../../Utils/SetupHandlers/reportSetUp"),logs:require("../../Utils/SetupHandlers/setLogs"),sugerencias:require("../../Utils/SetupHandlers/suggestSetUp"),"tempvoice-panel":require("../../Utils/SetupHandlers/tempvoicePanel"),tempvoice:require("../../Utils/SetupHandlers/tempvoiceSetUp"),tickets:require("../../Utils/SetupHandlers/ticketSetUp"),verificacion:require("../../Utils/SetupHandlers/verificationSystem"),welcome:require("../../Utils/SetupHandlers/welcomeSetUp")};
module.exports={data:new SlashCommandBuilder().setName("setup").setDescription("Configura los sistemas de Bryant's Oficial").setDefaultMemberPermissions(PermissionFlagsBits.Administrator).setDMPermission(false)
.addSubcommand(s=>s.setName("autorol").setDescription("Configura autoroles").addRoleOption(o=>o.setName("userrole").setDescription("Rol para usuarios").setRequired(true)).addRoleOption(o=>o.setName("botrole").setDescription("Rol para bots").setRequired(true)))
.addSubcommand(s=>s.setName("boost-preview").setDescription("Vista previa del sistema Booster"))
.addSubcommand(s=>s.setName("boost").setDescription("Configura Booster").addRoleOption(o=>o.setName("booster").setDescription("Rol Booster").setRequired(true)).addRoleOption(o=>o.setName("boostervip").setDescription("Rol Booster VIP").setRequired(true)).addRoleOption(o=>o.setName("boosterlegend").setDescription("Rol Booster Legend").setRequired(true)).addChannelOption(o=>o.setName("canal").setDescription("Canal de avisos").addChannelTypes(ChannelType.GuildText,ChannelType.GuildAnnouncement).setRequired(true)).addStringOption(o=>o.setName("descripcion").setDescription("Descripción. Variables: {usuario}, {servidor}, {boosts}").setMaxLength(4000)).addStringOption(o=>o.setName("thumbnail").setDescription("URL del thumbnail")).addStringOption(o=>o.setName("banner").setDescription("URL del banner superior")))
.addSubcommand(s=>s.setName("confesiones").setDescription("Configura confesiones").addChannelOption(o=>o.setName("channel").setDescription("Canal de confesiones").addChannelTypes(ChannelType.GuildText).setRequired(true)))
.addSubcommand(s=>s.setName("contador").setDescription("Configura el conteo").addChannelOption(o=>o.setName("channel").setDescription("Canal de conteo").addChannelTypes(ChannelType.GuildText).setRequired(true)))
.addSubcommand(s=>s.setName("salidas").setDescription("Configura las salidas").addChannelOption(o=>o.setName("channel").setDescription("Canal de salidas").addChannelTypes(ChannelType.GuildText).setRequired(true)).addStringOption(o=>o.setName("descripcion").setDescription("Descripción del mensaje")).addStringOption(o=>o.setName("banner").setDescription("URL del banner")))
.addSubcommand(s=>s.setName("reportes").setDescription("Configura reportes").addChannelOption(o=>o.setName("channel").setDescription("Canal de reportes").addChannelTypes(ChannelType.GuildText).setRequired(true)))
.addSubcommand(s=>s.setName("logs").setDescription("Configura logs").addChannelOption(o=>o.setName("canal").setDescription("Canal de logs").addChannelTypes(ChannelType.GuildText).setRequired(true)))
.addSubcommand(s=>s.setName("sugerencias").setDescription("Configura sugerencias").addChannelOption(o=>o.setName("channel").setDescription("Canal de sugerencias").addChannelTypes(ChannelType.GuildText).setRequired(true)))
.addSubcommand(s=>s.setName("tempvoice-panel").setDescription("Envía el panel global de TempVoice"))
.addSubcommand(s=>s.setName("tempvoice").setDescription("Configura TempVoice"))
.addSubcommand(s=>s.setName("tickets").setDescription("Configura tickets").addChannelOption(o=>o.setName("channel").setDescription("Canal del panel").addChannelTypes(ChannelType.GuildText).setRequired(true)).addChannelOption(o=>o.setName("channellogs").setDescription("Canal de logs").addChannelTypes(ChannelType.GuildText).setRequired(true)).addChannelOption(o=>o.setName("channelsupport").setDescription("Categoría soporte").addChannelTypes(ChannelType.GuildCategory).setRequired(true)).addChannelOption(o=>o.setName("channelbuy").setDescription("Categoría compra").addChannelTypes(ChannelType.GuildCategory).setRequired(true)).addRoleOption(o=>o.setName("handlers").setDescription("Rol del staff").setRequired(true)).addRoleOption(o=>o.setName("everyone").setDescription("Rol @everyone").setRequired(true)))
.addSubcommand(s=>s.setName("verificacion").setDescription("Configura verificación").addRoleOption(o=>o.setName("role").setDescription("Rol que recibirá").setRequired(true)).addRoleOption(o=>o.setName("remove_role").setDescription("Rol que se removerá").setRequired(true)).addStringOption(o=>o.setName("description").setDescription("Descripción del embed").setRequired(true)).addChannelOption(o=>o.setName("channel").setDescription("Canal").addChannelTypes(ChannelType.GuildText)).addAttachmentOption(o=>o.setName("thumbnail").setDescription("Thumbnail")).addAttachmentOption(o=>o.setName("image").setDescription("Imagen grande")).addStringOption(o=>o.setName("footer").setDescription("Footer")))
.addSubcommand(s=>s.setName("welcome").setDescription("Configura bienvenidas").addChannelOption(o=>o.setName("channel").setDescription("Canal de bienvenida").addChannelTypes(ChannelType.GuildText).setRequired(true)).addStringOption(o=>o.setName("color").setDescription("Color").addChoices({name:"Rojo",value:"#FF0000"},{name:"Blanco",value:"#FFFFFF"},{name:"Negro",value:"#000000"},{name:"Morado",value:"#8A2BE2"}).setRequired(true)).addStringOption(o=>o.setName("descripcion").setDescription("Descripción")).addStringOption(o=>o.setName("banner").setDescription("URL del banner")).addStringOption(o=>o.setName("thumbnail").setDescription("URL de thumbnail"))),
async execute(interaction){const h=handlers[interaction.options.getSubcommand()];if(!h?.execute)return interaction.reply({content:"❌ Configuración no disponible.",flags:64});return h.execute(interaction,interaction.client);}};